var searchData=
[
  ['flags_0',['Flags',['https://arm-software.github.io/CMSIS_6/v6.0.0/RTOS2/group__CMSIS__RTOS__EventFlags.html',0,'Event Flags'],['https://arm-software.github.io/CMSIS_6/v6.0.0/RTOS2/group__CMSIS__RTOS__ThreadFlagsMgmt.html',0,'Thread Flags']]],
  ['flags_20functions_1',['Flags Functions',['../group__rtx__evr__event__flags.html',1,'Event Flags Functions'],['../group__rtx__evr__thread__flags.html',1,'Thread Flags Functions']]],
  ['flags_20functions_20error_20codes_2',['Flags Functions Error Codes',['https://arm-software.github.io/CMSIS_6/v6.0.0/RTOS2/group__flags__error__codes.html',0,'']]],
  ['for_20armv6_20m_20v7_20m_3',['MPU Functions for Armv6-M/v7-M',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__mpu__functions.html',0,'']]],
  ['for_20armv8_201_20m_4',['for Armv8 1 M',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__pmu8__events__armv81.html',0,'PMU Events for Armv8.1-M'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__pmu8__functions.html',0,'PMU Functions for Armv8.1-M']]],
  ['for_20armv8_20m_5',['MPU Functions for Armv8-M',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__mpu8__functions.html',0,'']]],
  ['for_20armv8_20m_20v8_201_20m_6',['TrustZone for Armv8-M/v8.1-M',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__trustzone__functions.html',0,'']]],
  ['for_20cortex_20m55_7',['PMU Events for Cortex-M55',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__pmu8__events__armcm55.html',0,'']]],
  ['for_20cortex_20m85_8',['PMU Events for Cortex-M85',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__pmu8__events__armcm85.html',0,'']]],
  ['for_20cpu_20instructions_9',['Intrinsic Functions for CPU Instructions',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__intrinsic__CPU__gr.html',0,'']]],
  ['for_20simd_20instructions_10',['Intrinsic Functions for SIMD Instructions',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__intrinsic__SIMD__gr.html',0,'']]],
  ['fpu_20functions_11',['FPU Functions',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__fpu__functions.html',0,'']]],
  ['functions_12',['Functions',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__coreregister__trustzone__functions.html',0,'Core Register Access Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__Dcache__functions__m7.html',0,'D-Cache Functions'],['../group__rtx__evr__event__flags.html',1,'Event Flags Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__fpu__functions.html',0,'FPU Functions'],['../group__rtx5__specific__functions.html',1,'Functions'],['../group__rtx__evr__wait.html',1,'Generic Wait Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/RTOS2/group__CMSIS__RTOS__Wait.html',0,'Generic Wait Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__Icache__functions__m7.html',0,'I-Cache Functions'],['../group__rtx__evr__kernel.html',1,'Kernel Functions'],['../group__rtx__evr__memory.html',1,'Memory Functions'],['../group__rtx__evr__memory__pool.html',1,'Memory Pool Functions'],['../group__rtx__evr__message__queue.html',1,'Message Queue Functions'],['../group__rtx__evr__mutex.html',1,'Mutex Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__mve__functions.html',0,'MVE Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__nvic__trustzone__functions.html',0,'NVIC Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__sau__trustzone__functions.html',0,'SAU Functions'],['../group__rtx__evr__semaphore.html',1,'Semaphore Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__stacksealing__support__trustzone__functions.html',0,'Stack Sealing Support Functions'],['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__systick__trustzone__functions.html',0,'SysTick Functions'],['../group__rtx__evr__thread__flags.html',1,'Thread Flags Functions'],['../group__rtx__evr__thread.html',1,'Thread Functions'],['../group__rtx__evr__timer.html',1,'Timer Functions']]],
  ['functions_13',['Event functions',['../group__rtx__evr.html',1,'']]],
  ['functions_20error_20codes_14',['Flags Functions Error Codes',['https://arm-software.github.io/CMSIS_6/v6.0.0/RTOS2/group__flags__error__codes.html',0,'']]],
  ['functions_20for_20armv6_20m_20v7_20m_15',['MPU Functions for Armv6-M/v7-M',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__mpu__functions.html',0,'']]],
  ['functions_20for_20armv8_201_20m_16',['PMU Functions for Armv8.1-M',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__pmu8__functions.html',0,'']]],
  ['functions_20for_20armv8_20m_17',['MPU Functions for Armv8-M',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__mpu8__functions.html',0,'']]],
  ['functions_20for_20cpu_20instructions_18',['Intrinsic Functions for CPU Instructions',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__intrinsic__CPU__gr.html',0,'']]],
  ['functions_20for_20simd_20instructions_19',['Intrinsic Functions for SIMD Instructions',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__intrinsic__SIMD__gr.html',0,'']]],
  ['functions_20level_201_20',['Cache Functions (Level-1)',['https://arm-software.github.io/CMSIS_6/v6.0.0/Core/group__cache__functions__m7.html',0,'']]]
];
