name: Build documentation and pack
on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    if: |
      github.event_name != 'release' ||
      (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v'))
    name: Generate pack
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch tags
        if: github.event_name == 'release'
        run: |
          git fetch --tags --force

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.2
          packchk-version: 1.3.95
          gen-doc-script: ./CMSIS/DoxyGen/gen_doc.sh
          check-links-script: ./CMSIS/DoxyGen/check_links.sh
          doc-path: ./CMSIS/Documentation
          gen-pack-script: ./gen_pack.sh --no-preprocess
          gen-pack-output: ./output
          gh-pages-branch: gh-pages
