name: Build documentation and pack
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [ main ]
  release:
    types: [published]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  pack:
    if: |
      github.event_name != 'release' ||
      (github.event_name == 'release' && startsWith(github.ref, 'refs/tags/v'))
    name: Generate pack
    runs-on: ubuntu-20.04
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Fetch pre-built libs
        run: |
          ./CMSIS/RTOS2/RTX/Library/fetch_libs.sh

      - uses: Open-CMSIS-Pack/gen-pack-action@main
        with:
          doxygen-version: 1.9.6
          packchk-version: 1.4.1
          gen-doc-script: ./CMSIS/DoxyGen/gen_doc.sh
          check-links-script: ./CMSIS/DoxyGen/check_links.sh
          doc-path: ./CMSIS/Documentation/html
          gen-pack-script: ./gen_pack.sh --no-preprocess
          gen-pack-output: ./output
          gh-pages-branch: gh-pages
